device: cuda:0
note: k60_rad256_simplehept_2Layers_4Heads
seed: 42
log_tensorboard: false
num_threads: 5
resume: false
only_eval: false


model_name: trans_simplehept
model_kwargs:
  block_size: 100
  n_hashes: 1
  num_regions: 3  # 150 if tracking-60k
  pe_type: none
  num_heads: 4
  h_dim: 24
  n_layers: 2
  num_w_per_dist: 10


loss_name: infonce
loss_kwargs:
  dist_metric: l2_rbf
  tau: 0.05


optimizer_name: adam
num_epochs: 100
batch_size: 1
optimizer_kwargs:
  lr: 1.0e-3  # 1.0e-2 if tracking-60k


lr_scheduler_name: step
lr_scheduler_kwargs:
  gamma: 0.5
  step_size: 500


data_dir: ../data/
# dataset_name: tracking-6k
dataset_name: tracking-600
main_metric: accuracy@0.9
mode: max
